[package]
name = "music-jester"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.9.0", features = ["image"]}
iced_native = "0.10.3"
rodio = { version = "0.20.1", features = ["symphonia-all"] }
rfd = "0.15.3"
lofty = "0.15.0"
walkdir = "2"